pipeline {
    agent any

    stages {

        stage('Install Backend Dependencies') {
            steps {
                dir('fullstack-project/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Backend') {
            steps {
                dir('fullstack-project/backend') {
                    sh '''
                        if command -v pm2 > /dev/null; then
                            pm2 restart server || pm2 start server.js --name server
                        else
                            echo "PM2 is not installed"
                            nohup node server.js > server.log 2>&1 &
                        fi
                    ''
                }
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfullyy.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            echo 'Pipeline execution finished.'
        }
    }
}
